name: Build

on:
  push:
    branches: '**'
    tags: 'v*'
  pull_request:
    branches: '**'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./gradlew -b gradle/bootstrap.gradle bootstrap
        git describe --tags > VERSION.txt
        rm -rf .gradle gradle/.gradle .git
        zip -r harvest-git-bridge.zip .
    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: '{harvest-git-bridge.zip}'
        file_glob: true
        overwrite: true
